TorrentBOX/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from torrent import views as torrent_view

urlpatterns = [
    url(r'^$', torrent_view.index),
    url(r'^admin/', admin.site.urls),
    url(r'^torrent/', include('torrent.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

TorrentBox/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TorrentBox.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^api/', include('api.urls', namespace='api')),

    # FIXED ISSUE: 404 Not Found error when Debug set to False (https://github.com/L34p/TorrentBOX/issues/2)
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
)

accounts/urls.py
from django.conf.urls import url

from . import views

app_name = "accounts"
urlpatterns = [
    url(r'^sign_in/$', views.sign_in, name='sign_in'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^sign_out/$', views.sign_out, name='sign_out'),
]

torrent/urls.py
from django.conf.urls import url

from . import views

app_name = 'torrent'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^delete/(?P<torrent_id>\d+)/$', views.delete, name='delete'),
    url(r'^download/(?P<torrent_id>\d+)/$', views.download, name='download'),
    url(r'^status/$', views.status, name='status'),
]

TorrentBOX/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properities -->
  <title>TorrentBOX</title>
  {% load staticfiles %}

  <!-- Semantic-UI CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/site.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/reset.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/container.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/menu.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/segment.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/dropdown.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/icon.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/tab.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/button.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/input.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/progress.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/grid.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/list.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-ui/message.min.css' %}">

  <!-- TorrentBOX Custom CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/TorrentBOX.css' %}">
</head>

<body>
  <div class="ui fixed inverted menu">
    <div class="ui container">
      <div href="#" class="header item">
        <a href="/">TorrentBOX</a>
      </div>
      <div class="ui right simple dropdown item">
        <i class="inverted user large icon"></i>
        {{ request.user.username }}
        <div class="menu">
          <a class="item" href="{% url 'accounts:sign_out' %}">
            <i class="sign out big icon"></i> Sign out
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="ui main container">
    {% include "message.html" %}
    <div class="ui segment">
      <div class="ui secondary pointing menu">
        <a class="active item" data-tab="first">Add torrent link</a>
        <a class="item" data-tab="second">Upload torrent from PC</a>
      </div>

      <div class="ui tab active" data-tab="first">
        <form class="ui fluid action input" action="{% url 'torrent:add' %}" method="post">{% csrf_token %}
          <input type="text" id="torrent_url" name="torrent_url" placeholder="Paste here URL to torrent file">
          <button type="submit" class="ui teal button">
          Add torrent
          </button>
        </form>
      </div>
    
      <div class="ui tab" data-tab="second">
        <div class="ui secondary raised center aligned segment" id="dropbox">
          <br>
          <form enctype="multipart/form-data" action="{% url 'torrent:add' %}" method="post" style="margin-bottom:1em">{% csrf_token %}
            <div class="icon-upload">
              <label for="torrent_file">
                <i class="teal cloud upload link huge icon" type="file"></i>
              </label>
              <input type="file" id="torrent_file" name="torrent_file">
            </div>
          </form>
          To upload, drag torrents to here or <a href="#" id="upload_link">browse file</a> 
        </div>
      </div>
    </div>

    <!-- Torrent index block -->
    {% block content %} {% endblock %}
  </div>

  <!-- TorrentBOX Javascript -->
  <script src="{% static 'js/lib/jquery-3.1.0.min.js' %}"></script>
  <script src="{% static 'js/lib/jquery.dotdotdot.min.js' %}"></script>
  <script src="{% static 'js/semantic-ui/tab.min.js' %}"></script>
  <script src="{% static 'js/TorrentBOX.js' %}"></script>
</body>

</html>

TorrentBOX/templates/message.html
{% if messages %}
<div id="err-msg" class="ui negative message">
  <i class="close right icon" onclick="removeMessage()"></i></a>
  {% for message in messages %}
    {{ message }}
  {% endfor %}
</div>
{% endif %}