TorrentBOX/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from torrent import views as torrent_view

urlpatterns = [
    url(r'^$', torrent_view.index),
    url(r'^admin/', admin.site.urls),
    url(r'^torrent/', include('torrent.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

TorrentBox/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TorrentBox.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^api/', include('api.urls', namespace='api')),

    # FIXED ISSUE: 404 Not Found error when Debug set to False (https://github.com/L34p/TorrentBOX/issues/2)
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
)

accounts/urls.py
from django.conf.urls import url

from . import views

app_name = "accounts"
urlpatterns = [
    url(r'^sign_in/$', views.sign_in, name='sign_in'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^sign_out/$', views.sign_out, name='sign_out'),
]

torrent/urls.py
from django.conf.urls import url

from . import views

app_name = 'torrent'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^delete/(?P<torrent_id>\d+)/$', views.delete, name='delete'),
    url(r'^download/(?P<torrent_id>\d+)/$', views.download, name='download'),
    url(r'^status/$', views.status, name='status'),
]

accounts/models.py
from django.db import models

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class TorrentBoxCreateForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
            }
        )
    )

    password1 = forms.CharField(
        required=True,
        min_length=6,
        widget=forms.widgets.PasswordInput(
            attrs={
                'placeholder': 'Password',
            }
        )
    )

    password2 = forms.CharField(
        required=True,
        min_length=6,
        widget=forms.widgets.PasswordInput(
            attrs={
                'placeholder': 'Password confirm',
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def clean_username(self):
            return self.cleaned_data.get('username')


class TorrentBoxAuthForm(AuthenticationForm):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
            }
        )
    )

    password = forms.CharField(
        required=True,
        min_length=6,
        widget=forms.widgets.PasswordInput(
            attrs={
                'placeholder': 'Password',
            }
        )
    )

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import TorrentBoxAuthForm, TorrentBoxCreateForm


def sign_in(request):
    auth_form = TorrentBoxAuthForm(data=request.POST or None)
    create_form = TorrentBoxCreateForm(data=request.POST or None)
    template = 'accounts/sign_in.html'
    next_url = request.POST.get('next', '/')

    context = {
        'signin_form': auth_form,
        'signup_form': create_form,
        'next': next_url,
    }

    if request.method == 'POST':
        if auth_form.is_valid():
            login(request, auth_form.get_user())
            return redirect(next_url)
        else:
            messages.error(request, "Incorrect e-mail or password!")
            return render(request, template, context)

    return render(request, template, context)

def sign_up(request):
    auth_form = TorrentBoxAuthForm(data=request.POST or None)
    create_form = TorrentBoxCreateForm(data=request.POST or None)
    template = 'accounts/sign_in.html'
    next_url = request.POST.get('next', '/')

    context = {
        'signin_form': auth_form,
        'signup_form': create_form,
        'next': next_url,
    }

    if request.method == 'POST':
        if create_form.is_valid():
            username = create_form.clean_username()
            password = create_form.clean_password2()
            new_user = create_form.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('torrent:index')
        else:
            messages.error(request, "Invalid registration form")
            return render(request, template, context)

    else:
        return render(request, template, context)

@login_required
def sign_out(request):
    logout(request)
    return redirect('accounts:sign_in')

TorrentBOX/templates/accounts/sign_in.html
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>TorrentBOX</title>
    {% load staticfiles %}
    <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900|RobotoDraft:400,100,300,500,700,900'>
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="{% static 'css/accounts/style.css' %}">
  </head>
  <body>
    
  <!-- Form Mixin-->
  <div class="pen-title">
    <h1>TorrentBOX</h1><span><i class='fa fa-code'></i> by <a href='https://github.com/L34p/TorrentBOX'>l34p</a></span>
  </div>
  
  <!-- Form Module-->
  <div class="module form-module">
    <div class="toggle"><i class="fa fa-times fa-pencil"></i>
      <div class="tooltip">Register</div>
    </div>
    <div class="form">
      <h2>Login to your account</h2>
      <form method="post" action="{% url 'accounts:sign_in' %}">{% csrf_token %}
        {% for field in signin_form %}
          {{ field }}
        {% endfor %}
        <button type="submit">Login</button>
      </form>
    </div>
    <div class="form">
      <h2>Create an account</h2>
      <form method="post" action="{% url 'accounts:sign_up' %}">{% csrf_token %}
        {% for field in signup_form %}
          {{ field }}
        {% endfor %}
        <button type="submit">Register</button>
      </form>
    </div>
    {% if messages %}
    <div id="err-msg" class="cta">
      {% for message in messages %}
        {{ message }}
      {% endfor %}
    </div>
    {% endif %}
  </div>
  
   <script src="{% static 'js/lib/jquery-3.1.0.min.js' %}"></script>
   <script src="{% static 'js/accounts/index.js' %}"></script>
  </body>
</html>