TorrentBOX/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from torrent import views as torrent_view

urlpatterns = [
    url(r'^$', torrent_view.index),
    url(r'^admin/', admin.site.urls),
    url(r'^torrent/', include('torrent.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

TorrentBox/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TorrentBox.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^api/', include('api.urls', namespace='api')),

    # FIXED ISSUE: 404 Not Found error when Debug set to False (https://github.com/L34p/TorrentBOX/issues/2)
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
)

torrent/urls.py
from django.conf.urls import url

from . import views

app_name = 'torrent'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^delete/(?P<torrent_id>\d+)/$', views.delete, name='delete'),
    url(r'^download/(?P<torrent_id>\d+)/$', views.download, name='download'),
    url(r'^status/$', views.status, name='status'),
]

torrent/models.py
from django.contrib.auth.models import User
from django.db import models


class TorrentQuerySet(models.QuerySet):
    def copy_and_create(self, exist_torrent, new_owner):
        return self.create(
            name = exist_torrent.name,
            hash = exist_torrent.hash,
            size = exist_torrent.size,
            peers = exist_torrent.peers,
            status = exist_torrent.status,
            progress = exist_torrent.progress,
            download_rate = exist_torrent.download_rate,
            downloaded_size = exist_torrent.downloaded_size,
            owner = new_owner
        )
  
    def get_actives(self, owner):
        active_torrents = self.filter(status='downloading', owner=owner) 
        active_torrents |= self.filter(status='finished', owner=owner)
        active_torrents |= self.filter(status='compressing', owner=owner)
        return active_torrents

class Torrent(models.Model):
    name = models.CharField(max_length=200)
    hash = models.CharField(max_length=40)
    size = models.BigIntegerField(default=0)
    peers = models.PositiveSmallIntegerField(default=0)
    status = models.CharField(max_length=20)
    progress = models.PositiveSmallIntegerField(default=0)
    download_rate = models.FloatField(default=0)
    downloaded_size = models.BigIntegerField(default=0)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    objects = TorrentQuerySet.as_manager()

    class Meta:
        db_table = 'torrent_entries'
        verbose_name_plural = 'torrents'

    def __str__(self):
        return self.name

torrent/views.py
import os

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.validators import URLValidator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

import libtorrent as lt
from sendfile import sendfile

from .models import Torrent
from .tasks import download_torrent
from .utils import filesize, get_remain_time


@login_required
def index(request):
    torrents = Torrent.objects.get_actives(request.user)
    return render(request, 'torrent/index.html', {'torrents': torrents})

@login_required
def status(request):
    status_list = list()
    torrents = Torrent.objects.get_actives(request.user)

    for torrent in torrents:
        rtime = get_remain_time(torrent.size, torrent.downloaded_size, torrent.download_rate)
        status = dict(
            id = torrent.id,
            name = torrent.name,
            size = filesize(torrent.size),
            peers = torrent.peers,
            status = torrent.status,
            progress = torrent.progress,
            download_rate = filesize(torrent.download_rate, suffix='B/s'),
            downloaded_size = filesize(torrent.downloaded_size),
            rtime = rtime
        )

        status_list.append(status)

    return JsonResponse(status_list, safe=False)

@login_required
def download(request, torrent_id):
    torrent = get_object_or_404(Torrent, id=torrent_id, owner=request.user)

    # User can download only finished file
    if torrent.status == "finished":
        filepath = os.path.join(settings.SENDFILE_ROOT, torrent.name)
        return sendfile(request, filepath, attachment=True, attachment_filename=torrent.name)

    else:
        messages.error(request, "You can't download file until finished")
        return redirect('torrent:index')
   
@login_required
def delete(request, torrent_id):
    torrent = get_object_or_404(Torrent, id=torrent_id, owner=request.user)

    # Delete torrent entry but not delete real file in the server
    if torrent.status == 'finished':
        torrent.delete()
    
    # Torrent entry will be deleted by celery task
    elif torrent.status == 'downloading':
        torrent.status = 'terminated'
        torrent.save()

    elif torrent.status == 'queued':
        torrent.status = 'terminated'
        torrent.save()
        # XXX: Torrent is in the ready queue.
        # TODO: Add eviction functionality.

    return redirect('torrent:index')

@login_required
def add(request):
    # TODO: Support magnet URI
    if 'torrent_file' in request.FILES:
        torrent_file = request.FILES['torrent_file']
        torrent_data = torrent_file.read()

    elif 'torrent_url' in request.POST:
        url = request.POST['torrent_url']
        try:
            URLValidator(message='URL is not valid, please enter a valid URL')(url)
        except ValidationError as e:
            messages.error(request, e.message)
            return redirect('torrent:index')

        response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
        torrent_data = response.content

    else:
        return redirect('torrent:index')

    e = lt.bdecode(torrent_data)
    info = lt.torrent_info(e)
    torrent_hash = str(info.info_hash())

    # Current user already have this torrent
    if Torrent.objects.filter(owner=request.user, hash=torrent_hash).exists():
        return redirect('torrent:index')

    # Finished torrent file is already exist in the server
    exist_torrent = Torrent.objects.filter(hash=torrent_hash, status='finished').first()
    if exist_torrent:
        Torrent.objects.copy_and_create(exist_torrent, request.user)
        return redirect('torrent:index')

    new_torrent = Torrent.objects.create(
        name = info.name(),
        hash = torrent_hash,
        size = int(info.total_size()),
        peers = 0,
        status = 'queued',
        progress = 0,
        download_rate = 0,
        downloaded_size = 0,
        owner = request.user
    )

    download_torrent.delay(new_torrent.id, torrent_data)
    return redirect('torrent:index')

TorrentBOX/templates/torrent/index.html
{% extends 'base.html' %}
{% block content %}
{% load torrent_tags %}

<div class="ui segments" id="torrent-segments">
  <div class="ui segment">
    <i class="teal refresh icon"></i> DOWNLOADING TORRENTS
  </div>

  {% for torrent in torrents %}
  <div class="ui segment">
    <h4 class="ui header">
      <div class="ui grid">
        <div class="fourteen wide column dot-ellipsis dot-resize-update dot-height-20">
        {{ torrent.name }}
        </div>
        <div class="two wide column">
          <a href="{% url 'torrent:delete' torrent_id=torrent.id %}">
            <i class="large link black remove right icon"></i>
          </a>
        </div>
      </div>
    </h4>

    <div id="{{ torrent.id }}" class="ui indicating progress active" data-percent="{{ torrent.progress }}" style="margin-bottom:10px;">
      <div id="{{ torrent.id }}_bar" class="bar" style="transition-duration: 300ms; width: {{ torrent.progress }}%">
        <div id="{{ torrent.id }}_progress" class="progress">
        {{ torrent.progress }}%
        </div>
      </div>
    </div>

    <div id="{{ torrent.id }}_status" class="ui horizontal list">
      <div id="{{ torrent.id }}_drate" class="item">
        <i class="arrow circle down icon"></i>
        {{ torrent.download_rate|speedformat }} (peers: {{ torrent.peers }})
      </div>
      <div id="{{ torrent.id }}_dsize" class="item">
        <i class="download icon"></i>
        {{ torrent.downloaded_size|filesize }} / {{ torrent.size|filesize }}
      </div>
      <div id="{{ torrent.id }}_rtime" class="item">
        <i class="wait icon"></i> Remaining time: 
        {% get_remain_time torrent.size torrent.downloaded_size torrent.download_rate %}
      </div>
    </div>

    {% if torrent.status == 'finished' %}
    <a href="{% url 'torrent:download' torrent_id=torrent.id %}" class="ui tiny basic right floated button">
      <i class="arrow down large black icon"></i>Download
    </a>
    {% endif %}
  </div>
  
  {% empty %}
  <div class="ui segment">
    <div class="ui secondary raised center aligned segment">
     <br><br>
     <i class="disabled refresh massive icon"></i>
     <h3>No active downloads</h3>
     <p>There are no torrents downloading at the moment.</p>
     <p>Add torrent to download!</p>
     <br><br>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}